services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: aviron
      POSTGRES_USER: aviron
      POSTGRES_DB: aviron
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aviron -d aviron" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  web:
    build: .
    container_name: web
    ports:
      - "8080:8080"
    environment:
      DB_HOSTNAME: db
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
